### ISSUE TITLE
Auto Number Manager incompatible with my version of XrmToolBox ??

### ISSUE THREAD

**Issue by markkusuominen** [rappen/AutoNumManager#1]
Hi, when trying to install "Auto Number Manager" I get message "Auto Number Manager incompatible with the current version of XrmToolBox". In XrmToolBox I selected "About" -> "Checked for update" and got result "No update available!"

Also "Auto Number Manager" text was red in Plugins Store. Not sure what to do, is it something on my end or maybe something else? ;-)

Thanks in advance!

**Comment by rappen** [comment]
That is correct. The Plugin supports a not yet released version of XTB, as we are waiting for official SDK to be released.
If you go to Releases here on GitHub, there is a prerelease available. 
https://github.com/rappen/AutoNumManager/releases

**Comment by markkusuominen** [comment]
Ok, thanks for the info!
