### ISSUE TITLE
Populate autonumber field of existing records

### ISSUE THREAD

**Issue by sanjaya-yapa** [rappen/AutoNumManager#10]
Hi Jonas,
I have used auto numbering in one of the entities and it works fine for the newly created records. But the challenge I face is with existing records. I need to update the existing records and the existing records does not have a number on them. 
I have searched for this and could not find a solution. I really appreciate if you could guide me with any solution.

Thanks
Sanjaya

**Comment by rappen** [comment]
Hi Sanjaya,
Unfortunately this is not possible, this feature only triggers before records are created.

**Comment by sanjaya-yapa** [comment]
Hi Jonas,
Appreciate your quick response. One other question I have.
Now I have created the Auto numbering field in the Development Environment using the XRMToolBox Plugin. It appears within the solution. So when I deploy it to Test, UAT and Production Environments, do I have to use the Plugin configure the fields in the target environments mentioned above. I assume, since it is a customization, I don't have to reconfigure it in the target environment.
Thanks
Sanjaya

**Comment by rappen** [comment]
Hi,
I think MS have fixed the problem that auto number formats were not included in the solution files!
The seed however is not included, so you might want to set that after importing the managed solution to the target environment.
See comment I got just yesterday here: http://jonasrapp.innofactor.se/2017/10/anm.html?showComment=1526375193407#c1583069511609783492

**Comment by sanjaya-yapa** [comment]
Thanks for the information provided. Was very helpful.
