### ISSUE TITLE
Autonumber configured for account.accountnumber is not working

### ISSUE THREAD

**Issue by zenecamickeyd** [rappen/AutoNumManager#11]
I spun up a new D365O trial (9.0.2.1470) and configured the account.accountnumber field as per the attached screenshot, but when I create a new account record the accountnumber field is not assigned an auto-number.

![auto number manager account accountnumber configuration](https://user-images.githubusercontent.com/38660190/44907121-d9cc6a80-ad0e-11e8-9d33-29866c6a8f06.png)

**Comment by zenecamickeyd** [comment]
I just updated the Auto Number Manager plugin to v1.2018.8.1 but this hasn't fixed this issue.

**Comment by rappen** [comment]
Can you verify that the field is not populated with a value from the UI?
You are creating the account in the UI? (not from portal etc)
Unified Interface or Classic?
You write "D365O Trial" - what do you mean with the "O"?

**Comment by zenecamickeyd** [comment]
The "O" stands for "online" - sorry for the confusion.

I am creating accounts via the classic interface.  

I added the Account Number field to the main Account form and I can see that this field does not contain any data for the accounts I created today.  I also ran an Advanced Find looking for accounts where Account Number contains data and Created On = today, and no records were returned.

**Comment by rappen** [comment]
Hm...
No solutions installed, no plugin or workflow triggering on create account?
Did you try simply recreating the autonum format?
Maybe it could affect things that you changed the max length of the field to 6 characters.
What happens if you create a new field with auto number?

Regarding seed, this is not possible to read from CRM, that is why it is always empty, even after you actively set it. The "Guess seqnum" button will read existing data, use the autonum format string to try to parse the highest value of existing records, and in that way do a best guess on current value.

**Comment by zenecamickeyd** [comment]
It looks like your suggestion that reducing the size of the field is what caused this issue was correct.  I think may have been because there were existing sample accounts in the trial whose Account Numbers were greater than 7 characters in length.  

What's a little weird is that when I opened the Auto Number Manager against my trial this morning the auto-number on the account.accountnumber field had disappeared - the field had been reset to its default configuration.

I re-added the auto-number configuration to account.accountnumber
- set Seed to 1638
- left Maximum Length set to the default 20 characters
and now when I create a new account record the Account Number field is populated as configured.

This is great news as I can now use this tool in our Sandbox and Production instances and get rid of a 3rd party auto-number solution.

Thanks for your help.

**Comment by rappen** [comment]
Great news!
I get a bit worried though that the auto number format was somehow lost from the attribute...
Any idea if the organization was updated over the weekend?
You could try using the *Solution History* tool in XrmToolBox to see if there were any solution imports recently. It might show something, but I'm not sure you the whole truth there.

**Comment by zenecamickeyd** [comment]
There were 4 solutions updated on Saturday:
- msdynce_CustomerServiceHubPatch v9.0.20.0163
- msdynce_SalesPrimaryFieldRename v9.0.4.565
- msdynce_SchedulingUpgrade v9.0.0.0
- CustomControlsCore v9.0.0002.1470

**Comment by rappen** [comment]
Just checked these solutions in my own org, and they don't seem to contain any entities. I had an idea that updated might have overwritten the attribute properties.
So no explanation there.
I would be very interested in hearing if this behavior appears again though!
Closing this issue for now, feel free to reopen or create a new if needed.
