### ISSUE TITLE
Guess current SEQNUM not displaying correctly

### ISSUE THREAD

**Issue by ckupferschmid** [rappen/AutoNumManager#12]
We have successfully adjusted the seed to 500000 on standard entity case auto number.
When now 'Guessing current SEQNUM' the value returned is 50000.

Seems to be an display issue.
Auto Number Manager Version 1.2018.8.1

**Comment by rappen** [comment]
Have you created new records where the adjusted seed has been used?
The "Guess" function looks at existing data (last created record) and parses the value in the number attribute with respect to the number format and extracts the sequence part of it.

**Comment by rappen** [comment]
Closing after no feedback. Feel free to reopen and supply more info.
