### ISSUE TITLE
Question: 2 number sequences one entity 

### ISSUE THREAD

**Issue by thomassandsor** [rappen/AutoNumManager#14]
Example account:
Create one sequence for account type customer, and one sequence for account type vendor?

I only want to write to one field, and not have to use workflow afterword to replace the "account number" field.

Probably not supported by the sdk directly, but needed to ask if possible adding the if in the beginning :)

**Comment by rappen** [comment]
Hi Thomas,
This does not work with the OOB feature in the platform.
As you suspect, you would have to create some workflow or similar to accomplish it.
Or use some 3rd party solutions out there.
