### ISSUE TITLE
Autonumbering doesn't take effect

### ISSUE THREAD

**Issue by anasraf** [rappen/AutoNumManager#15]
I installed Auto numbering Plugin from xrmtoolbox i select opportunity entity then i entered the auto numbering format when i click update everything end successfully but when create new opportunity in my online instance nothing happens

**Comment by rappen** [comment]
Can you try reopening ANM and verify that the numbering format you entered is there?
I know there have been some caching issues with metadata in D365 Online instances, that may be what is causing this.
If so, the recommendation is simply "wait a while"... 😕

**Comment by anasraf** [comment]
I uninstalled ANM and installed it again i tried changing my numbering format to a simple sequence number it doesn't work  neither updating my xrmtoolbox 
Ps : My online instance is v9.1 and in french language

**Comment by rappen** [comment]
Oh uninstalling/reinstalling ANM should not affect anything as long as you are using latest version.
What entity/attribute are you working with?
Can you provide the sample numbering format you use?
After you set the format, close and reopen ANM, what format is then shown on the attribute?

**Comment by anasraf** [comment]
I work on opportunity Entity i am trying to autonumber the name attribute

this is my sample format : CBI-{DATETIMEUTC:yyyyMMdd}-{SEQNUM:4}

after i set the format nothing happen it asks me to enter the name of the opportunity manually as it was in the OOB

**Comment by rappen** [comment]
If the `Name` attribute on the Opportunity form is required, the user must enter a name.
If the attribute that is being numbered already contains a value when it is saved to the server, the auto numbering feature will not replace the existing value.
So to be able to get automatic Name for the opportunity, you have to change the attribute to not required, and make the field read-only on the form.
Setting the auto number format will not automatically change how the form looks and works.
This is how the core platform feature of auto number formats work, not something controlled by ANM.

**Comment by anasraf** [comment]
No it doesn't work i tested all what you said above i make it read only and i made the field optional

**Comment by rappen** [comment]
After you set the format, close and reopen ANM, what format is then shown on the attribute?

**Comment by anasraf** [comment]
it shows the same format i entered before XXX-{DATETIMEUTC:yyyyMMdd}-{SEQNUM:4}

**Comment by rappen** [comment]
That is positive, at least.
Ok, something is telling CRM to keep the value (empty, I guess) instead of populating it from the number format...
Are you using classic web interface for creating the new opportunities?
And you are creating new, not just updating existing?
Can you provide a screenshot before/after saving?

**Comment by anasraf** [comment]
I found the problem i was applying a business process and i putted the name in the process flow when i deleted everything works like magic thank you very much for your time 👍

**Comment by rappen** [comment]
Great to hear it worked out! 😎
