### ISSUE TITLE
After using DATETIMEUTC not able to access via UI

### ISSUE THREAD

**Issue by Roxxinger** [rappen/AutoNumManager#16]
Hi,

after I changed the Numberformat to {DATETIMEUTC:yy}-{SEQNUM:5}-{RANDSTRING:6} instead of 19-{SEQNUM:5}-{RANDSTRING:6} I can't access the autonumbering in CRM anymore. Error is the generic CRM error: please try again...contact your administrator. ![autonumbering_error](https://user-images.githubusercontent.com/38560916/51321077-21575700-1a62-11e9-8b35-e20e8288a49c.png)When i switch back it works again.

Any Ideas what could be causing this?

Thanks,
Jan

**Comment by rappen** [comment]
Unfortunately the autonum features in the CRM UI does not support everything that the autonum features in the platform supports. So this is a bug/flaw/limitation in the CRM UI.
I would recommend reporting this issue to Microsoft, as your numbering format is completely valid according to their own specs.

**Comment by Roxxinger** [comment]
Ok, I've thought of something like that :( Thanks for your answer.

**Comment by rappen** [comment]
I raised the question with MS without a relevant answer yet. But please submit an issue to highlight the problem.
