### ISSUE TITLE
not all entities in solution will be displayed in Autonummanager

### ISSUE THREAD

**Issue by bryce2071** [rappen/AutoNumManager#17]
Hi Jonas, 

not all entities in solution will be displayed in autonummanger, so they cant be choosen.
any idea?
thx. 
sincerly peter

**Comment by rappen** [comment]
Any specific entities you don't see?
Custom, standard, system...?

**Comment by bryce2071** [comment]
no, 2 custom entities are showed, but most not.
I`ll try to send a screenshot if this is possible here.

**Comment by rappen** [comment]
It is possible, you can just take a screenshot and paste here with ctrl+v.

**Comment by rappen** [comment]
@bryce2071 Did you ever find a solution or pattern to this?
I have not been able to repro.

**Comment by rappen** [comment]
Please reopen if there is still a problem.
