### ISSUE TITLE
Seed is not a valid number

### ISSUE THREAD

**Issue by thiashton** [rappen/AutoNumManager#20]
While trying to update existing auto-number field , facing the error "Seed is not a valid number".
Attached screenshot for reference.

![Auto Number Manager Issue](https://user-images.githubusercontent.com/50176887/60658108-71787900-9e4a-11e9-9623-d756c7061758.jpg)

**Comment by thiashton** [comment]
Wrong Seed value

**Comment by rappen** [comment]
Hi - the seed should only be the numeric part, so if you enter `10978` it should be fine.
Please try this and if it works you can close this issue :)
