### ISSUE TITLE
Unexpected seed counter jump

### ISSUE THREAD

**Issue by KLee-Dynamics** [rappen/AutoNumManager#25]
Hi there,

We encountered an issue where the seed counter "jumps" up quite a few counters between consective records (XXX-607 to XXX-632) without any explanation. We have checked the audit summaries and server logs but there seem to be no explanation as to why or how this occur.

Can you think of how this could possibly occur? So far it's happened only once.

I'll try and see if I can get a screenshot if you think it might help.

Thank you and best regards.

**Comment by rappen** [comment]
Hi KLee
I cannot explain/understand why this would happen.
From the perspective of this tool, it only sets the numbering format and seed, after that it has no awareness of what the platform feature actually does.
Sorry....

**Comment by rappen** [comment]
Please reopen if it's still a problem.
