### ISSUE TITLE
The number sequence seems to be broken

### ISSUE THREAD

**Issue by Aunnisa** [rappen/AutoNumManager#47]
It's started generating duplicate values i.e. XXXX1120. There are existing records in CRM with values until XXXX2428. 

Any idea on how to fix it so the number starts with XXXX2429 not XXXX1121

**Comment by rappen** [comment]
Hi @Aunnisa 

You may set the seed (next number) in the tool. You can do this without changing the numbering format, just telling the system to "give this number to the next record being created" and continue from there.

![image](https://user-images.githubusercontent.com/2572253/91324546-7f155e80-e7c2-11ea-8375-2bb23dfca0fc.png)

**Comment by Aunnisa** [comment]
Hi Jonas,

I tried doing that but after saving, the data is set back to default seed.  The value should be 2427.

Thanks,

**Comment by rappen** [comment]
Not sure I understand...
Note that setting the seed will only affect the numbered value of future records that are created, it does in no way change existing data.

**Comment by rappen** [comment]
Please reopen if it's still a problem.
