### ISSUE TITLE
Autonumber not generated when record is created from Dynamics Portals

### ISSUE THREAD

**Issue by elaizabenitez** [rappen/AutoNumManager#5]
Hi @rappen 

If the record is created in Dynamics 365, the autonumber is generated in the desired field.
If the record is created from Dynamics Portals, the autonumber is not generated in the desired field.

![image](https://user-images.githubusercontent.com/34328017/33698324-d42762a0-db5f-11e7-8a5b-c57b933ca48a.png)

**Comment by rappen** [comment]
Interesting observation!
I don't see however how this could be related to the ANM tool, I suggest you open a ticket with MS for this.
I'd love to see what they say about it, so please post a link to the ticket here, if that is ok with you :)

**Comment by rappen** [comment]
My guess @benitezhere is that the portal includes this attribute in the entity posted for create to crm. The numbering feature is designed to respect explicitly given values, even when it is null.
Numbers will only be assigned if the attribute is not present in the attribute collection of the record to create.

**Comment by readyxrm** [comment]
I found that if the autonumber field is editable on the entity form, even if you don't add any data to it, it will not generate an auto-number.  Fix would be to make it read-only or remove from the form.
![portalautonumber](https://user-images.githubusercontent.com/18264651/42277098-3025134c-7f64-11e8-8ba4-749c35f48a05.jpg)

**Comment by rappen** [comment]
Closing as problem is in Portals, not in CRM and even less in ANM.
