### ISSUE TITLE
Maximum limit on Seed too low

### ISSUE THREAD

**Issue by syntax922** [rappen/AutoNumManager#7]
I had a requirement to have an autonumber start at 6billion. Unfortunately the tool does not allow a seed that high. I was able to successfully create a console app and set the seed and it works fine. Is it possible to update the tool?

**Comment by rappen** [comment]
Quite possible!
In the mean time, you could add auto number format:
``6000{SEQNUM:6}``  (or similar)

**Comment by syntax922** [comment]
That is an awesome work around! Sorry I didn't think of it :-)

**Comment by syntax922** [comment]
@rappen any estimate on an ETA for this?

**Comment by rappen** [comment]
@syntax922 it is now available in version 1.2018.3.1.
