### ISSUE TITLE
Unable to unlock disabled auto numbering field 

### ISSUE THREAD

**Issue by ASA8282** [rappen/AutoNumManager#8]
Hi,

I have enabled auto-numbering on a primary field on a custom entity and subsequently disabled the auto numbering because there are old records that require to be added to the custom entity records.

The attribute remained locked in the form after I have disabled the auto-numbering feature. I have tried to unlock using OOB attribute properties and also using Bulk Form Attribute Manager from XRMToolbox but it failed to unlock it.

Pls help.

**Comment by rappen** [comment]
Hi Asa

Unfortunately, this is not something that is in the control of AutoNumManager. This tool simply consumes the SDK methods available to set the Auto Number Format on attributes.
I suggest you contact Microsoft for support with this issue.

/Jonas

**Comment by ASA8282** [comment]
Noted. I am working with Msft support team on the issue.

Sent from my iPhone

On 9 May 2018, at 2:28 PM, Jonas Rapp <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Asa

Unfortunately, this is not something that is in the control of AutoNumManager. This tool simply consumes the SDK methods available to set the Auto Number Format on attributes.
I suggest you contact Microsoft for support with this issue.

/Jonas
