### ISSUE TITLE
Unable to change the seed of the default Quote Number field

### ISSUE THREAD

**Issue by antonjw** [rappen/AutoNumManager#9]
Hi Jonas,

I was trying to change the seed of the OOB Quote Number field for a customer who just upgraded to v9, however AutoNumberManager returns an error when I confirm this change.

Should this be possible with the AutoNumberManager?  It would be pretty nice to be able to do, to work around the inability to override the seed in the UI... 

[![Screen_Shot_2018-05-09_at_14.21.29.png](https://s7.postimg.cc/n3xc11eiz/Screen_Shot_2018-05-09_at_14.21.29.png)](https://postimg.cc/image/51499tio7/)

Many thanks,
Anton

**Comment by rappen** [comment]
Thanks for reporting this, I will look into it and see if I can repro and hopefully find a solution. 👍

**Comment by jamazz** [comment]
Hi Jonas, 
any news on this one? I am having the exact same problem. Also i get the same error when changing the format. 

Thanks in advance
Jannes

**Comment by rappen** [comment]
I have not been able to find information about this, I recommend opening a case with Microsoft.

**Comment by jamazz** [comment]
I will consider doing it in the future. For now i think we will stick with another solution. Thanks for your quick answer though.

**Comment by rappen** [comment]
Come to think of it, I can probably release a fix for this quite soon.
ANM shouldn't have to touch the `RequiredLevel` of the attribute.

**Comment by rappen** [comment]
@antonjw @jamazz Updated version is now available in the Plugins Store in XrmToolBox!

**Comment by jamazz** [comment]
Just opened the toolbox and saw an update for the plugin. Seems to be working now.

Thanks a lot, this is making things much easier for us!
